In [1]:
import pandas as pd
from openpyxl import load_workbook

In [3]:
df = pd.read_excel('productSales.xlsx')
df

       product  sales
0        Apple     15
1       Banana     13
2   Strawberry     16
3   Watermelon     16
4        Apple     46
5       Banana     34
6   Strawberry     67
7   Watermelon     35
8        Apple     23
9       Banana     56
10  Strawberry     32
11  Watermelon     45

In [4]:
grouped_df = df.groupby('product')['sales'].sum().reset_index()

In [5]:
grouped_df

      product  sales
0       Apple     84
1      Banana    103
2  Strawberry    115
3  Watermelon     96

In [7]:
with pd.ExcelWriter('sales_report.xlsx', engine='openpyxl') as writer:
    grouped_df.to_excel(writer, sheet_name='Summary', index=False)